blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/spicycentral/SpicyCentral/discussions
    about: Please ask and answer questions here
  - name: Security Vulnerabilities
    url: https://github.com/spicycentral/SpicyCentral/SECURITY.md
    about: Please report security vulnerabilities according to our security policy